### ISSUE TITLE
imagesLoaded and percentPosition explanation

### ISSUE THREAD

**Issue by spacecat** [metafizzy/flickity-docs#43]
Hi,

It would be nice if a visually before and after illustration could be provided to better understand exactly what these two properties do.

I've read the docs and checked and experimented with the codepens several times but I don't see the difference when toggling these variables. Neither do I see any difference in my own application.

Regards,
/P

**Comment by desandro** [comment]
Thank you for this feedback. Both options are hard to visualize.
- `imagesLoaded: true` is useful to reposition cells after images have been loaded. If your cell sizes is determined by a containing image, then you should use `imagesLoaded: true` or `lazyLoad: true`. [Try viewing the demo](http://codepen.io/desandro/pen/MYQWEe), with `imagesLoaded: false` and your cache disabled to see why its useful.
- `percentPosition: false` will set the position of cells in pixels. This is useful if your cells have pixel widths, instead of percent widths. It's useful if you need pixel perfect position of your cells.
